logins = (
    'Atai','Sultan','Adinai','Ermek',
    'Aslan','Liazat','Salavat','Daniyar',
    'Bolot','Alymbek','Joomart','Aibek',
    'Aibek','Konstantin','Oliver','Jake',
    'Noah','James','Jack','Connor','Liam',
    'John','Harry','Callum','Mason','Robert',
    'Jacob','Jacob','Jacob','Michael','Charlie',
    'Kyle','William','William','Thomas','Joe',
    'Ethan','David','George','Reece','Michael',
    'Richard','Oscar','Rhys','Alexander','Joseph',
    'James','Charlie','James','Charles','William',
    'Damian','Daniel','Thomas','Amelia','Margaret',
    'Emma','Mary','Olivia','Samantha','Olivia',
    'Patricia','Isla','Bethany','Sophia',
    'Jennifer','Emily','Elizabeth','Isabella',
    'Elizabeth','Poppy','Joanne','Ava','Linda',
    'Ava','Megan','Mia','Barbara','Isabella','Victoria',
    'Emily','Susan','Jessica','Lauren','Abigail',
    'Margaret','Lily','Michelle','Madison','Jessica',
    'Sophie','Tracy','Charlotte','Sarah', 'qwerty',
    'test_user','test_test','user123','user_user', 'bzzzz', 'Erbol'
)

domains = ('@gmail.com','@yandex.com','@bk.ru','@outlook.com','@mail.ru','@icloud.com')


streets = ('Ленина', 'Курманжан-Датка','Баялинова','Масалиева','Алиева','Салиева','Горького','Культурная','Джим','Киевская','Памирская','Клубная','Таджиксая','Жибек жолу','Кокум-Бий','Мамажанова','Мамырова','Ташкентская')


professions = (
    'Cloud Architect',
    'Cloud Consultant',
    'Cloud Product and Project Manager',
    'Cloud Services Developer',
    'Cloud Software and Network Engineer',
    'Cloud System Administrator',
    'Cloud System Engineer',
    'Computer and Information Research Scientist',
    'Computer and Information Systems Manager',
    'Computer Network Architect',
    'Computer Systems Analyst',
    'Computer Systems Manager',
    'IT Analyst',
    'IT Coordinator',
    'Network Administrator',
    'Network Architect',
    'Network and Computer Systems Administrator',
    'Network Engineer',
    'Network Systems Administrator',
    'Senior Network Architect',
    'Senior Network Engineer',
    'Senior Network System Administrator',
    'Telecommunications Specialist',
    'Customer Support Administrator',
    'Customer Support Specialist',
    'Desktop Support Manager',
    'Desktop Support Specialist',
    'Help Desk Specialist',
    'Help Desk Technician',
    'IT Support Manager',
    'IT Support Specialist',
    'IT Systems Administrator',
    'Senior Support Specialist',
    'Senior System Administrator',
    'Support Specialist',
    'Systems Administrator',
    'Technical Specialist',
    'Technical Support Engineer',
    'Technical Support Specialist',
    'Data Center Support Specialist',
    'Data Quality Manager',
    'Database Administrator',
    'Senior Database Administrator',
    'Application Support Analyst',
    'Senior System Analyst',
    'Systems Analyst',
    'Systems Designer',
    'Chief Information Officer (CIO)',
    'Chief Technology Officer (CTO)',
    'Director of Technology',
    'IT Director',
    'IT Manager',
    'Management Information Systems Director',
    'Technical Operations Officer',
    'Information Security',
    'Security Specialist',
    'Senior Security Specialist',
    'Application Developer',
    'Applications Engineer',
    'Associate Developer',
    'Computer Programmer',
    'Developer',
    'Java Developer',
    'Junior Software Engineer',
    '.NET Developer',
    'Programmer',
    'Programmer Analyst',
    'Senior Applications Engineer',
    'Senior Programmer',
    'Senior Programmer Analyst',
    'Senior Software Engineer',
    'Senior System Architect',
    'Senior System Designer',
    'Senior Systems Software Engineer',
    'Software Architect',
    'Software Developer',
    'Software Engineer',
    'Software Quality Assurance Analyst',
    'System Architect',
    'Systems Software Engineer',
    'Front End Developer',
    'Senior Web Administrator',
    'Senior Web Developer',
    'Web Administrator',
    'Web Developer',
    'Webmaster'
)


countries = (
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
)

pswd_symbols = (
    'A', 'a', 'B', 'b', 'C', 'c', 
    'D', 'd', 'E', 'e', 'F', 'f', 
    'G', 'g', 'H', 'h', 'I', 'i', 
    'J', 'j', 'K', 'k', 'L', 'l', 
    'M', 'm', 'N', 'n', 'O', 'o', 
    'P', 'p', 'Q', 'q', 'R', 'r', 
    'S', 's', 'T', 't', 'U', 'u', 
    'V', 'v', 'W', 'w', 'X', 'x', 
    'Y', 'y', 'Z', 'z', '1', '2', 
    '3', '5', '6', '7', '8', '9', '0'
)